# Generated by Django 3.0.4 on 2022-03-01 18:43

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='area',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(default=datetime.datetime(2022, 3, 1, 18, 43, 3, 568579, tzinfo=utc), max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='America/Santo_Domingo'),
        ),
    ]
